apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: client-integration-test
  namespace: wavesmusicplayer
spec:
  args:
  - name: service-name
  metrics:
  - name: client-integration-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: client-integration-test
                image: ghcr.io/wavesmp/wavesmp/client-integration-test:aedcb22769ebfa304c3af9918f424f91531d4ac9
                args:
                - "./integration-test.sh"
                - "http://{{args.service-name}}"
              restartPolicy: Never
