apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: server-integration-test
  namespace: wavesmusicplayer
spec:
  args:
  - name: service-name
  metrics:
  - name: server-integration-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: server-integration-test
                image: ghcr.io/wavesmp/wavesmp/server-integration-test:123003c1e233f44ad83984e1b38db603219b4823
                env:
                - name: WAVESMP_TEST_HOST
                  value: "{{args.service-name}}"
              restartPolicy: Never
