apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: server-integration-test
  namespace: wavesmp
spec:
  args:
  - name: service-name
  metrics:
  - name: server-integration-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: server-integration-test
                image: ghcr.io/wavesmp/wavesmp/server-integration-test:aedcb22769ebfa304c3af9918f424f91531d4ac9
                env:
                - name: WAVESMP_TEST_HOST
                  value: "{{args.service-name}}"
              restartPolicy: Never
