apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: server-integration-test
  namespace: wavesmusicplayer
spec:
  args:
  - name: service-name
  metrics:
  - name: server-integration-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: server-integration-test
                image: busybox
                command: [echo]
                args: ["Running server integration tests for {{args.service-name}}"]
              restartPolicy: Never
