apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: server-integration-test
  namespace: wavesmusicplayer
spec:
  args:
  - name: service-name
  metrics:
  - name: server-integration-test
    provider:
      job:
        spec:
          backoffLimit: 1
          activeDeadlineSeconds: 600
          template:
            spec:
              containers:
              - name: server-integration-test
                image: ghcr.io/wavesmp/wavesmp/server-integration-test:1f57185c4503be6b115a8c7cac1c94838ac5ec64
                env:
                - name: WAVESMP_TEST_HOST
                  value: "{{args.service-name}}"
              restartPolicy: Never
